[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefix=."

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  framework = "vite"
  targetPort = 5173
